#!/usr/bin/bash

PATH=/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

# Exit if any command fails
set -o errexit

IMAPSYNC_VERSION="1.945"

MUNIN_PLUGINS="
"

echo "* Activate munin plugins"
/opt/qutic/bin/munin-node-plugins ${MUNIN_PLUGINS}

echo "* Setup imapsync home"
groupadd -g 1210 imapsync
useradd -m -s /usr/bin/bash -d /home/imapsync -u 1210 -g imapsync imapsync
passwd -N imapsync
passwd -d imapsync

echo "* Install imapsync"
# https://github.com/imapsync/imapsync
curl -LO -s https://download.qutic.com/src/imapsync/imapsync-imapsync-${IMAPSYNC_VERSION}.tar.gz
gtar xf imapsync-imapsync-${IMAPSYNC_VERSION}.tar.gz
mv imapsync-imapsync-${IMAPSYNC_VERSION}/imapsync /opt/local/bin/imapsync
mkdir -p /opt/local/share/doc/imapsync
mv imapsync-imapsync-${IMAPSYNC_VERSION}/README /opt/local/share/doc/imapsync/README
rm imapsync-imapsync-${IMAPSYNC_VERSION}.tar.gz
rm -rf imapsync-imapsync-${IMAPSYNC_VERSION}
mkdir -p /var/log/imapsync
chown imapsync:imapsync /var/log/imapsync

echo "* Install missing perl modules"
/opt/local/bin/cpanm Sys::MemInfo

# Clean up
echo "* Cleaning up."
pkgin -y rm gmake gcc7
rm /root/customize

# Prepare image for provisioning
sm-prepare-image -y
